### ISSUE TITLE
about tta

### ISSUE THREAD

**Issue by liudi-didi** [thomeou/SALSA#1]
Hi，Is there no code for TTA？I can't find it

**Comment by thomeou** [comment]
Hi,

I did not include the TTA for this code. You can write your own TTA using the FOA/MIC rotation in transform.

**Comment by liudi-didi** [comment]
> Hi,
> 
> I did not include the TTA for this code. You can write your own TTA using the FOA/MIC rotation in transform.

OK，thanks！
