### ISSUE TITLE
Need help in running the code 

### ISSUE THREAD

**Issue by OmarObaya** [thomeou/SALSA#10]
I need help to run the code i already extracted the salsa features but i have problems in train and evaluate even after appling the instructions in the read me file. Can some one help me please

**Comment by Peter-72** [comment]
@OmarObaya Hi Omar, What are your problems exactly?

**Comment by OmarObaya** [comment]
All my problems are related to path even though i followed all the data arrangement inside the code

**Comment by Peter-72** [comment]
@OmarObaya Solutions have been discussed in #2. If you still have problems after this, tag me again.

**Comment by OmarObaya** [comment]
> @OmarObaya Solutions have been discussed in #2. If you still have problems after this, tag me again.

Can we arrange an online meeting and help me run the code on my laptop?
