### ISSUE TITLE
On-the-fly parallelized+refactored SALSA and SALSA-Lite

### ISSUE THREAD

**Issue by andres-fr** [thomeou/SALSA#4]
Hi there,

Me again. I reimplemented the SALSA and SALSA-Lite features to work on-the-fly with any number of microphones. I wanted to share it with you and the community with the hope it will help advance the field. The implementation can be found in this gist (I'm happy to make a PR if appropriate):

https://gist.github.com/andres-fr/d923e1df7de4dd6e0af34b28a2a7ef04

It should be just plug&play (docstrings contain usage examples), and depends only on `numpy` and `librosa`. I'd love some feedback! I did some sandbox tests and results were identical (up to eigenvector +/- sign), but no rigorous utests. Data looks fine though, here is an example from the DCASE 2021 SEDL dataset with the default parameters (wav file `fold1_room1_mix001.wav`):

### LogMel excerpt

![snippet_logmel](https://user-images.githubusercontent.com/4235319/154383144-870d549a-5b19-48bb-b262-9086cb73834a.png)

### SALSA excerpt

![snippet_salsa](https://user-images.githubusercontent.com/4235319/154383172-e3b024de-b35f-455f-b1b0-7fe3370f326f.png)

### SALSA-Lite excerpt

![snippet_salsa_lite](https://user-images.githubusercontent.com/4235319/154383184-9b72bd44-45be-4dc0-bebf-88bdf000a712.png)

Note that a main visual difference is due to the fact that SALSA has the noise floor + coherence filters, which remove a lot of clutter (for readers: the SALSA-Lite paper kind of shows that these are not really needed).

The parallelized SALSA version yielded a decent speedup that could make it particularly useful for data augmentation techniques that are applied on the waveform. Also (hopefully) the refactoring helps coming up with further exciting variations of SALSA. For the record I like salsa brava.

Cheers!  
Andres

**Comment by dberghi** [comment]
Thank you, Andres. Computing the frequency bins in parallel is very useful!

**Comment by andres-fr** [comment]
Thanks a lot!

One side note, I am not sure what is the role of the sign invariance of the eigendecomposition. I mean, if we decompose the spatial covariance matrix `M` (Hermitian) as follows:

```python
M = U * Lambda * U.T
```

Then we can clearly see that multiplying `U` by `-1` yields the exact same M. This has the effect of adding 180 degrees to the phase. Numerically, it seems that the solutions are consistent (I just saw very few discrepancies with my implementation) but I wonder if this could be introducing some noise or overhead into the network.

**Comment by karnwatcharasupat** [comment]
Hi @andres-fr, many thanks for working on this and so sorry for the very late reply (both of us have been very very busy lately). 

I will discuss more with @thomeou about the sign issue, but a neural network should be robust enough to this kind of noise. 

Please feel free to create PR and I will take a look at it. Thank you!

**Comment by andres-fr** [comment]
Hi @karnwatcharasupat thanks for getting back.

Taking a closer look at it, integrating this particular enhancement into the repo would require some substantial changes, for 2 main reasons:
1. I did a pretty good amount of refactoring. My gist does not depend on any of the repo's code, and this was intended:
  * The script is this way stand-alone
  * I refactored things like the heuristic `SalsaNoiseFloorTracker` to make the code more understandable
  * Refactored the SALSA computations to make them vectorized
  * General OOP, DRY, on-the-fly changes
2. The repo is not designed to run on-the-fly computations: it makes a very good job at making the results of the paper reproducible, but this is done so in a batched manner.

Therefore, I think that properly integrating the gist into the repo would require refactoring the repo itself to match the building blocks from the gist, and to make it realtime-ready by basically creating a pipeline and possibly a pip python package with `__main__.py` functionality.

On the other hand, we can just "add" the gist as a stand-alone script into the repo root and update the `README` accordingly. This is arguably a much cleaner solution, and way less effort. What do you think?

Cheers and thanks again!  
Andres

**Comment by karnwatcharasupat** [comment]
I like your solution as well. In the future we will probably have to do a major housekeeping to convert the repo into a more package-like style as more people are using it. At the moment, I think you can create a PR (so you are shown as contributor as well), and add the gist into the repo. I think we could put it in a subfolder `/contrib/<your contrib name>/` for now, until I have time to better integrate and test it with the main code.

Thanks a lot!

**Comment by karnwatcharasupat** [comment]
@andres-fr I just gave you access to my old on-the-fly SALSA code for PyTorch. Please feel free to use code snippets from there as well.
